// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQvr0uawqArddZBDnXdNmqmRUFnZHkmwc',
    appId: '1:385373412650:web:792b945ba4c4eb337b5253',
    messagingSenderId: '385373412650',
    projectId: 'bs-rashhuli',
    authDomain: 'bs-rashhuli.firebaseapp.com',
    storageBucket: 'bs-rashhuli.appspot.com',
    measurementId: 'G-8K5MZF5W36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8TeGgw0sP9wyFaLfpAAWXhvj5ruPWE5o',
    appId: '1:385373412650:android:62ef9a53d63f9d2c7b5253',
    messagingSenderId: '385373412650',
    projectId: 'bs-rashhuli',
    storageBucket: 'bs-rashhuli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcegVPEiJE_6GAB605SqfNU8rHUYy9VGY',
    appId: '1:385373412650:ios:35098f50cdd2afe17b5253',
    messagingSenderId: '385373412650',
    projectId: 'bs-rashhuli',
    storageBucket: 'bs-rashhuli.appspot.com',
    iosBundleId: 'com.example.bsRashhuli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcegVPEiJE_6GAB605SqfNU8rHUYy9VGY',
    appId: '1:385373412650:ios:35098f50cdd2afe17b5253',
    messagingSenderId: '385373412650',
    projectId: 'bs-rashhuli',
    storageBucket: 'bs-rashhuli.appspot.com',
    iosBundleId: 'com.example.bsRashhuli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQvr0uawqArddZBDnXdNmqmRUFnZHkmwc',
    appId: '1:385373412650:web:cc502e6ef69c42867b5253',
    messagingSenderId: '385373412650',
    projectId: 'bs-rashhuli',
    authDomain: 'bs-rashhuli.firebaseapp.com',
    storageBucket: 'bs-rashhuli.appspot.com',
    measurementId: 'G-2JC53683N3',
  );

}